# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#pETUSOtWO#
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 518)
        MainWindow.setIconSize(QtCore.QSize(15, 15))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(450, 500))
        self.frame.setMaximumSize(QtCore.QSize(450, 500))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(107, 61, 58);\n"
"border-radius: 15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(430, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(430, 50))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color: rgb(63, 0, 0);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setStyleSheet("QLabel{\n"
"color: white;\n"
"font: 15pt \"SansSerif\";\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btn_close = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_close.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_close.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"background-color: rgb(170, 150, 158);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(93, 69, 127);\n"
"}\n"
"")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(20, 20))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(430, 170))
        self.frame_3.setMaximumSize(QtCore.QSize(430, 16777215))
        self.frame_3.setStyleSheet("QLabel{\n"
"font: 13pt;\n"
"color: white;\n"
"}\n"
"QFrame{\n"
"background-color: rgb(63, 0, 0);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(400, 30))
        self.label_2.setMaximumSize(QtCore.QSize(400, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setMinimumSize(QtCore.QSize(410, 70))
        self.label_3.setMaximumSize(QtCore.QSize(410, 70))
        self.label_3.setStyleSheet("QLabel{\n"
"font: 13pt;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setMinimumSize(QtCore.QSize(420, 110))
        self.label_4.setMaximumSize(QtCore.QSize(420, 110))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_5.setMinimumSize(QtCore.QSize(420, 110))
        self.label_5.setMaximumSize(QtCore.QSize(420, 110))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setMinimumSize(QtCore.QSize(410, 30))
        self.label_6.setMaximumSize(QtCore.QSize(410, 30))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Mensajes Automaticos | Whatsapp"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; text-decoration: underline;\">Seccion Ayuda:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">En el </span><span style=\" font-size:8pt; text-decoration: underline;\">recuadro primero</span><span style=\" font-size:8pt;\"> es donde debe ir nuestro mensaje a mandar,<br> </span><span style=\" font-size:8pt;\">este puede tener cualquier caracter y la cantidad que querramos.</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">En el </span><span style=\" font-size:8pt; text-decoration: underline;\">segundo recuadro</span><span style=\" font-size:8pt;\"> <br>es donde debe ir los numeros telefonicos a mandar el mensaje.<br> Puede ser uno y tambien varios, si son varios numeros debemos<br> de separarlos con una coma \',\'. <br>Los numeros telefonicos deben ir con el codigo del pais: (+54, +51, etc).</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">En el </span><span style=\" font-size:8pt; text-decoration: underline;\">tercer recuadro</span><span style=\" font-size:8pt;\"><br/>es donde debe ir el tiempo en segundos, esto solo funciona si son <br>varios numeros, hace referencia el tiempo que demorara en enviar<br> el mismo mensaje al otro numero.</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Hecho Por QwertySalazar -"))
